# Generated by Django 5.0.6 on 2024-07-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='personName',
        ),
    ]
