# Generated by Django 5.0.6 on 2024-07-04 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0004_drinks_delete_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinks',
            old_name='drink',
            new_name='drink_name',
        ),
    ]
